document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("			<title>精中集团</title>");
document.writeln("			<link href=\'css/1024-1200.css\' rel=\'stylesheet\' type=\'text/css\' media=\'all\' />");
document.writeln("			<link href=\'css/1200-1920.css\' rel=\'stylesheet\' type=\'text/css\'/>");
document.writeln("			<meta name=\'viewport\' content=\'width=device-width,initial-scale=1.0\' />");
document.writeln("			<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />");
document.writeln("			<script src=\'js/jquery-1.11.1.min.js\'></script>");
document.writeln("			<link rel=\'stylesheet\' href=\'css/swiper.min.css\'>");
document.writeln("			<script src=\'js/swiper.min.js\'></script>        ");
document.writeln("			<script src=\'js/swiper.animate1.0.2.min.js\'></script>");
document.writeln("			<script src=\'js/main.js\'></script>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div class=\'footer\'>");
document.writeln("			<div class=\'footer-con\'>			");
document.writeln("				<label>版权所有：上海精中教育集团  Copyright (C) 2013 TOMATO ART SCHOOL All Rights Reserved    网站备案号：沪ICP备16025500号-1</label>			");
document.writeln("			</div>			");
document.writeln("		</div>");
document.writeln("		<!--");
document.writeln("        	作者：804446554@qq.com");
document.writeln("        	时间：2017-03-22");
document.writeln("        	描述：");
document.writeln("        	<a href=\'#0\' class=\'cd-top\'>Top</a>");
document.writeln("        -->");
document.writeln("		");
document.writeln("		<a href=\'#0\' class=\'cd-top\'>Top</a>");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");