document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<title>精中集团</title>");
document.writeln("		<link href=\'css/1024-1200.css\' rel=\'stylesheet\' type=\'text/css\' media=\'all\' />");
document.writeln("		<link href=\'css/1200-1920.css\' rel=\'stylesheet\' type=\'text/css\'/>		");
document.writeln("		<meta name=\'viewport\' content=\'width=device-width,initial-scale=1.0\' />");
document.writeln("		<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />");
document.writeln("		<script src=\'js/jquery-1.11.1.min.js\'></script>");
document.writeln("		<link rel=\'stylesheet\' href=\'css/swiper.min.css\'>");
document.writeln("		<script src=\'js/swiper.min.js\'></script>        ");
document.writeln("		<script src=\'js/swiper.animate1.0.2.min.js\'></script>");
document.writeln("		<script src=\'js/main.js\'></script>");
document.writeln("		");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div class=\'header\'>");
document.writeln("			<div class=\'header-top\'>");
document.writeln("				<div class=\'con\'>");
document.writeln("					<label>您好，欢迎进入上海精中教育集团官方网站！</label>");
document.writeln("					<label class=\'label1\'>做受人最尊敬的中国教育！</label>");
document.writeln("					<label class=\'label1\'>服务热线: 021-63817688</label>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("			</div>");
document.writeln("			<div class=\'header-bot\'>");
document.writeln("				<div class=\'con\' id=\'dao\'>");
document.writeln("					<div class=\'logo\'>");
document.writeln("					 	<img src=\'img/logo.png\'>					 ");
document.writeln("					 </div>");
document.writeln("					 <div class=\'menu\'>");
document.writeln("					 	<ul>");
document.writeln("					 		<li><a id=\'shouye\' style=\'color: #FFFFFF;\' href=\'index.html\'>首页</a><span>•</span></li>");
document.writeln("					 		<li><a id=\'guanyu\'>走进精中</a><span>•</span></li>");
document.writeln("					 		<li><a id=\'pinpai\'>品牌项目</a><span>•</span></li>");
document.writeln("					 		<li><a id=\'zixun\'>新闻资讯</a><span>•</span></li>");
document.writeln("                             <li><a id=\'anli\'>加盟案例</a><span>•</span></li>");
document.writeln("					 		<li><a id=\'lianxi\'>联系我们</a></li>");
document.writeln("					 	</ul>");
document.writeln("					 </div>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("				<!--隐藏导航 -->");
document.writeln("				<div class=\'yin-dao\' id=\'yin-dao\'>");
document.writeln("					<div class=\'yin-con\'>");
document.writeln("						<div class=\'yin-logo\'>");
document.writeln("						 	<img src=\'img/logo.png\'>					 ");
document.writeln("						 </div>");
document.writeln("						 <div class=\'yin-menu\'>");
document.writeln("						 	<ul>");
document.writeln("						 		<li><a id=\'shouyes\'  href=\'index.html\'>首页</a><span>•</span></li>");
document.writeln("						 		<li><a id=\'guanyus\'>走进精中</a><span>•</span></li>");
document.writeln("						 		<li><a id=\'pinpais\'>品牌项目</a><span>•</span></li>");
document.writeln("						 		<li><a id=\'zixuns\'>新闻资讯</a><span>•</span></li>");
document.writeln("                                <li><a id=\'anlis\'>加盟案例</a><span>•</span></li>");
document.writeln("						 		<li><a id=\'lianxis\'>联系我们</a></li>");
document.writeln("						 	</ul>");
document.writeln("						 </div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("				");
document.writeln("				<div class=\'banner\'>");
document.writeln("						<!--轮播-->					");
document.writeln("					<div class=\'swiper-container\'>");
document.writeln("					    <div class=\'swiper-wrapper\' >");
document.writeln("					    	<div class=\'swiper-slide\'  style=\'background: url(img/banner2.png) center center no-repeat;background-size:100% 100%;\'></div>");
document.writeln("					        <div class=\'swiper-slide\'  style=\'background: url(img/banner1.png) center center no-repeat;background-size:100% 100%;\'></div>");
document.writeln("					        <div class=\'swiper-slide\' style=\'background: url(img/banner3.png) center center no-repeat;background-size:100% 100%;\'></div>");
document.writeln("					        <div class=\'swiper-slide\' style=\'background: url(img/banner4.png) center center no-repeat;background-size:100% 100%;\'></div>");
document.writeln("					        ");
document.writeln("					    </div>");
document.writeln("					    <!-- 如果需要分页器 -->");
document.writeln("					    <div class=\'swiper-pagination\'></div> 			        ");
document.writeln("					    <!-- 如果需要导航按钮 -->");
document.writeln("					    <div class=\'swiper-button-prev\'></div>");
document.writeln("					    <div class=\'swiper-button-next\'></div>		    ");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("				<div class=\'wenben\' id=\'shangfan\'>");
document.writeln("					<div id=\'holder\'>						");
document.writeln("						<ul>");
document.writeln("							<li><span style=\'color: #F5F7FD;float: left;size: 18px;margin-right: 30px;\'>●</span><a href=\'http://www.chinafqt.com/archives/577.html\' target=\'_blank\'>遇见蕃茄田艺术，遇见爱!</a></li>");
document.writeln("							<li><span style=\'color: #F5F7FD;float: left;size: 18px;margin-right: 30px;\'>●</span><a href=\'http://www.chinafqt.com/archives/121.html \' target=\'_blank\'>卢崇真讲座：教学现场中的艺术：让人和人之间发生有故事的交往！</a></li>");
document.writeln("							<li><span style=\'color: #F5F7FD;float: left;size: 18px;margin-right: 30px;\'>●</span><a href=\'http://www.chinafqt.com/archives/18.html\' target=\'_blank\'>东盟会议促教育前行，精中教育集团让艺术走进每个家庭</a></li>");
document.writeln("							<li><span style=\'color: #F5F7FD;float: left;size: 18px;margin-right: 30px;\'>●</span><a href=\'http://www.gymboglobal.com.cn/xihe/newsshow/id/56544\' target=\'_blank\'>微课堂】善解童贞，破开那些不能说的秘密 | 父母微课堂 第23期</a></li>");
document.writeln("							<li><span style=\'color: #F5F7FD;float: left;size: 18px;margin-right: 30px;\'>●</span><a href=\'http://www.touchbox.com/articles/302\' target=\'_blank\'>亲子陪伴，一本书就能让孩子变“有趣”？！</a></li>");
document.writeln("							<li><span style=\'color: #F5F7FD;float: left;size: 18px;margin-right: 30px;\'>●</span><a href=\'http://www.playabc.com.cn/index.php?ts=newscontent&menuid=5&aid=27\' target=\'_blank\'>英语和射箭，也许更配哦</a></li>");
document.writeln("							<li><span style=\'color: #F5F7FD;float: left;size: 18px;margin-right: 30px;\'>●</span><a href=\'https://mp.weixin.qq.com/s?__biz=MzIxMDM3NTU3Mw==&mid=2247484233&idx=1&sn=7d858bf5f2ddd8a4a3dfd9ed0fd7b064&chksm=9764c5b3a0134ca562468aaa41f33e7938c453fed4c6ded1df5b19dc5a6c2a3116208cea946e#rd\' target=\'_blank\'>「为何来中国深耕？」韩国汉松教育集团董事长真情告白</a> </li>");
document.writeln("							<li><span style=\'color: #F5F7FD;float: left;size: 18px;margin-right: 30px;\'>●</span><a href=\'https://mp.weixin.qq.com/s?__biz=MzIxMDM3NTU3Mw==&mid=2247484187&idx=1&sn=5229b2761c47acbd92705cb6aa140273&chksm=9764c5e1a0134cf7bddd5be46d57303635071c5ba5fba245f7998bc984b99f7d4088f7ea63f5#rd\' target=\'_blank\'>终于，我们来了！精韩家访 本周五正式开幕 （文末有彩蛋）</a></li>");
document.writeln("							<li><span style=\'color: #F5F7FD;float: left;size: 18px;margin-right: 30px;\'>●</span><a href=\'http://www.chinafqt.com/archives/100.html \'>致海口市蕃茄田艺术的感谢信</a> </li>");
document.writeln("							<li><span style=\'color: #F5F7FD;float: left;size: 18px;margin-right: 30px;\'>●</span><a href=\'http://www.chinafqt.com/archives/194.html \'>招商加盟——和蕃茄田艺术一起，为孩子未来撑起一片天空!</a> </li>");
document.writeln("						</ul>			");
document.writeln("					</div>");
document.writeln("					");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			");
document.writeln("		</div>");
document.writeln("	</body>");
document.writeln("	<script type=\'text/javascript\'>");
document.writeln("		");
document.writeln("		  var swiper = new Swiper(\'.swiper-container\', { ");
document.writeln("	         pagination: \'.swiper-pagination\', ");
document.writeln("	         loop:\'true\',");
document.writeln("	         paginationClickable: \'.swiper-pagination\', ");
document.writeln("	         nextButton: \'.swiper-button-next\', ");
document.writeln("	         prevButton: \'.swiper-button-prev\', ");
document.writeln("	         spaceBetween: 30, ");
document.writeln("	         autoplayDisableOnInteraction : false,  //鼠标点击一下true的时候停止自动播放，false会继续自动播放       ");
document.writeln("	         grabCursor: true, ");
document.writeln("	    	 paginationClickable: true, ");
document.writeln("	    	 autoplay: 5000,");
document.writeln("	    	 followFinger:false,");
document.writeln("	         effect: \'coverflow\'   ");
document.writeln("	     }); ");
document.writeln("	     ");
document.writeln("	     function marquee(height,speed,delay){");
document.writeln("			//alert(height);");
document.writeln("			var scrollT;");
document.writeln("			var pause = false;");
document.writeln("			var ScrollBox = document.getElementById(\'shangfan\');");
document.writeln("			//alert(ScrollBox);");
document.writeln("			if(document.getElementById(\'holder\').offsetHeight <= height) return;");
document.writeln("			var _tmp = ScrollBox.innerHTML.replace(\'holder\', \'holder2\')");
document.writeln("			ScrollBox.innerHTML += _tmp;");
document.writeln("			ScrollBox.onmouseover = function(){pause = true}");
document.writeln("			ScrollBox.onmouseout = function(){pause = false}");
document.writeln("			ScrollBox.scrollTop = 0;");
document.writeln("			function start(){");
document.writeln("			     scrollT = setInterval(scrolling,speed);");
document.writeln("			     if(!pause) ScrollBox.scrollTop += 2;");
document.writeln("			}");
document.writeln("			function scrolling(){");
document.writeln("			     if(ScrollBox.scrollTop % height != 0){");
document.writeln("			         ScrollBox.scrollTop += 2;");
document.writeln("			         if(ScrollBox.scrollTop >= ScrollBox.scrollHeight/2) ScrollBox.scrollTop = 0;");
document.writeln("			     }");
document.writeln("			   else{");
document.writeln("			         clearInterval(scrollT);");
document.writeln("			         setTimeout(start,delay);");
document.writeln("			     }");
document.writeln("			}");
document.writeln("			setTimeout(start,delay);");
document.writeln("		}");
document.writeln("		marquee(24,10,2000);");
document.writeln("	</script>");
document.writeln("</html>");
document.writeln("");